config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'dashboard#index'

  resources :mountains  
  get 'profile', to: "profile#show", as: :user_profile

end

app/models/mountain.rb
class Mountain < ActiveRecord::Base
    belongs_to :user
    has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/sample-1.jpg"
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
    validates_presence_of :name, :elevation

end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :mountains
  has_one :profile
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    # goes to the database and runs the RAW SQL: select * from mountains;
    @mountains = current_user.mountains
  end
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  before_action :find_mountain, only: [:show, :edit, :update, :destroy]

  def index
    @mountains = Mountain.all
  end

  def show
  end

  def new
    @mountain = current_user.mountains.new
  end

  def create
    @mountain = current_user.mountains.new(mountain_params)
    if @mountain.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @mountain.update(mountain_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @mountain.destroy
    redirect_to root_path
  end

  private
    def mountain_params
      params.require(:mountain).permit(:name, :elevation, :difficulty, :distance, :notes, :picture)
    end

    def find_mountain
      @mountain = current_user.mountains.find(params[:id])
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
    @all_mountains = Mountain.all
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/mountains_helper.rb
module MountainsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/dashboard/index.html.haml
.center
  = link_to "click here to add a mountain of your choice!", new_mountain_path, class: "btn blue darken-4"
  = link_to "All Mountains!", mountains_path, class: "btn blue darken-4mngfi3"
  
= render(partial: 'shared/mountains')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MountainTrackr
    = stylesheet_link_tag    'application', media: 'all'
    %link{:href => "http://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body.grey.darken-4.white-text
    %p.notice= notice
    %p.alert= alert
    %nav.blue.darken-4
      .nav-wrapper
        %a.brand-logo{:href => "/"} Mountain Trackr
        %a.button-collapse{"data-activates" => "mobile-demo", :href => "#"}
          %i.material-icons menu
        %ul.right.hide-on-med-and-down
          %li
            = link_to "dashboard", root_path
          %li
            = link_to "profile", user_profile_path
          %li
            = link_to "Log out", destroy_user_session_path, method: :delete, data: {confirm: " are you sure you want to log out?"}
        %ul#mobile-demo.side-nav
          %li
            = link_to "dashboard", root_path
          %li
            = link_to "profile", user_profile_path
          %li
            = link_to "Log out", destroy_user_session_path, method: :delete, data: {confirm: " are you sure you want to log out?"}
    %br
    = yield

app/views/mountains/_mountain_form.haml
.container
  = form_for @mountain do |f|
    .input-field
      = f.label :name
      = f.text_field :name, required: true
  
    .input-field
      = f.label :elevation
      = f.text_field :elevation, required: true
  
    .input-field
      = f.label :difficulty
      = f.select :difficulty, (1..10).to_a
  
    .input-field
      = f.label :distance
      = f.text_field :distance

    .input-field
      = f.file_field :picture  
  
    .input-field
      = f.label :notes
      = f.text_area :notes, class: "materialize-textarea"

    .center
      = f.submit 'Save', class: "btn blue darken-4"
      = link_to "Back", root_path, class: 'btn grey darken-2'

app/views/mountains/edit.html.haml
%h3.center 
  edit mountain #{@mountain.name}
= render(partial: "mountain_form")

app/views/mountains/index.haml
%h3.center All Mountains
%hr
.center
  = link_to 'Dashboard', root_path, class: 'btn'
= render(partial: 'shared/mountains')

app/views/mountains/new.html.haml
%h3.center new mountain
= render(partial: "mountain_form")

app/views/mountains/show.html.haml
.container
  .center
    = link_to 'Dashboard', root_path, class: 'btn'
  .row
    .col.s12
      .card
        .card-image
          %img{src: @mountain.picture.url}
            %span.card-title
              = @mountain.name
        .card-content.black-text
          %label Elevation:
          %p 
            = @mountain.elevation
          %label Distance:
          %p 
            = @mountain.distance
          %label Difficulty:
          %p 
            = @mountain.difficulty
          %label Notes:
          %p
            = @mountain.notes

app/views/shared/_mountains.haml
- if @mountains.any?
  .row
    - @mountains.each do |mountain|
      .col.s12.m4
        .card
          .card-image
            %img.mountain-picture{:src => mountain.picture.url}
              %span.card-title
                = mountain.name
          .card-content
            %p.black-text
              = mountain.notes
          .card-action
            = link_to "Show", mountain_path(mountain)
            = link_to "Edit", edit_mountain_path(mountain)
            = link_to "Delete", mountain_path(mountain), method: :delete, data: {confirm: 'Really delete this mountain?'}
- else
  %h5.center
    No Mountains yet, Get climbing!